export const POST_SEARCH_LIST_REQUEST = 'POST_SEARCH_LIST_REQUEST';
export const POST_SEARCH_LIST_SUCCESS = 'POST_SEARCH_LIST_SUCCESS';
export const POST_SEARCH_LIST_FAIL = 'POST_SEARCH_LIST_FAIL';

export const POST_DASHBOARD_REQUEST = 'POST_DASHBOARD_REQUEST';
export const POST_DASHBOARD_SUCCESS = 'POST_DASHBOARD_SUCCESS';
export const POST_DASHBOARD_FAIL = 'POST_DASHBOARD_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
