# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing node dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Running ESLint Linter
        run: npm run lint --if-present
        working-directory: ./frontend

      - name: Running Stylelint
        run: npm run stylelint --if-present
        working-directory: ./frontend

      - name: Running Prettier Code Formatter
        run: npm run format:check --if-present
        working-directory: ./frontend

      - name: Performing React build
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Performing React tests if any defined
        run: npm test
        working-directory: ./frontend

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./frontend
      #     start: npm start
